title: Youth Exchange USA
author: GitHub User
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Hallo Hier schreibe ich ein Wenig um euch Ã¼ber meinen Austausch zu informieren

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
